"use strict";
exports.__esModule = true;
exports.S_IFMT = 61440;
exports.S_IFSOCK = 49152;
exports.S_IFLNK = 40960;
exports.S_IFREG = 32768;
exports.S_IFBLK = 24576;
exports.S_IFDIR = 16384;
exports.S_IFCHR = 8192;
exports.S_IFIFO = 4096;
exports.S_ISUID = 2048;
exports.S_ISGID = 1024;
exports.S_ISVTX = 512;
exports.S_ISLNK = function (m) { return (((m) & exports.S_IFMT) === exports.S_IFLNK); };
exports.S_ISREG = function (m) { return (((m) & exports.S_IFMT) === exports.S_IFREG); };
exports.S_ISDIR = function (m) { return (((m) & exports.S_IFMT) === exports.S_IFDIR); };
exports.S_ISCHR = function (m) { return (((m) & exports.S_IFMT) === exports.S_IFCHR); };
exports.S_ISBLK = function (m) { return (((m) & exports.S_IFMT) === exports.S_IFBLK); };
exports.S_ISFIFO = function (m) { return (((m) & exports.S_IFMT) === exports.S_IFIFO); };
exports.S_ISSOCK = function (m) { return (((m) & exports.S_IFMT) === exports.S_IFSOCK); };
exports.S_IRWXU = 448;
exports.S_IRUSR = 256;
exports.S_IWUSR = 128;
exports.S_IXUSR = 64;
exports.S_IRWXG = 56;
exports.S_IRGRP = 32;
exports.S_IWGRP = 16;
exports.S_IXGRP = 8;
exports.S_IRWXO = 7;
exports.S_IROTH = 4;
exports.S_IWOTH = 2;
exports.S_IXOTH = 1;
